name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  index-posts:
    runs-on: ubuntu-latest
    steps:
      - name: bun setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: bun install
      - name: index posts
        run: bun run scripts/index-posts.ts
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: posts/index.json
          default_author: github_actions
