name: CI
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{secrets.GH_ACCESS_TOKEN}}" \
          -d '{"ref":"master"}' \
          --fail-with-body \
          https://api.github.com/repos/nsaunders/nsaunders.dev/actions/workflows/build.yml/dispatches
